// <auto-generated />
using DemoAjaxCallController.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DemoAjaxCallController.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191025103454_add-codogymer")]
    partial class addcodogymer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DemoAjaxCallController.Models.Codegymer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDepTrai");

                    b.Property<bool>("IsGiau");

                    b.Property<bool>("IsThongMinh");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Codegymers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDepTrai = false,
                            IsGiau = false,
                            IsThongMinh = false,
                            Name = "Le Van Bon"
                        },
                        new
                        {
                            Id = 2,
                            IsDepTrai = false,
                            IsGiau = false,
                            IsThongMinh = false,
                            Name = "Nguyen Van Quy"
                        },
                        new
                        {
                            Id = 3,
                            IsDepTrai = false,
                            IsGiau = false,
                            IsThongMinh = false,
                            Name = "Bui Hoang Long"
                        },
                        new
                        {
                            Id = 4,
                            IsDepTrai = false,
                            IsGiau = false,
                            IsThongMinh = false,
                            Name = "Phan Van My"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
